### ISSUE TITLE
Allow a custom fonts directory via a filter on the directory in use.

### ISSUE THREAD

**Issue by pattonwebz** [WPTT/webfont-loader#1]
https://github.com/WPTT/webfont-loader/blob/4496f034c7b086437bb9c8cd8299fa50bd8ff1ab/wptt-webfont-loader.php#L91-L93

The linked code as well as a number of other places in the script assume a specific directory for the fonts to exist. I would like this directory to be a filtered location because in some hosting plans the filesystem is locked down. In one of my test sites creation of files/folders directly inside the wp-content directory is forbidden so I only have 2 options:

1. Create the `/wp-content/fonts` directory manually - in advance of it being used.
2. Use a different directory to store the files.

**Comment by aristath** [comment]
Done in #6
