### ISSUE TITLE
Fonts do not update if I switch format

### ISSUE THREAD

**Issue by gsarig** [WPTT/webfont-loader#7]
Hi,

I noticed the following issue: If I load the fonts as woff2 and then regret it and add the WOFF parameter for IE compatibility, the local fonts folder keeps containing the WOFF2 version, and vice versa. Basically, it's whatever loads first. After that, if you want to override the setting you need to manually remove the fonts folder and reload the page to fetch the fonts again. 

Ideally, this switch should be handled from within the script, either by re-downloading the fonts when the format changes or by downloading both versions and load whichever is set in wp_enqueue_style accordingly.

**Comment by aristath** [comment]
Good catch :+1: 
Should be OK now.
